# Generated by Django 2.0.3 on 2018-04-08 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='airhumi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NODE', models.IntegerField()),
                ('DATA', models.IntegerField()),
                ('CREATETIME', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='airtemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NODE', models.IntegerField()),
                ('DATA', models.FloatField(max_length=5)),
                ('CREATETIME', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='co2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NODE', models.IntegerField()),
                ('DATA', models.FloatField(max_length=5)),
                ('CREATETIME', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LAMP', models.BooleanField(max_length=1)),
                ('PUMP', models.BooleanField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='light',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NODE', models.IntegerField()),
                ('DATA', models.IntegerField()),
                ('CREATETIME', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='soilhumi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NODE', models.IntegerField()),
                ('DATA', models.IntegerField()),
                ('CREATETIME', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='soiltemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NODE', models.IntegerField()),
                ('DATA', models.FloatField(max_length=5)),
                ('CREATETIME', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('UID', models.IntegerField(primary_key=True, serialize=False)),
                ('ACCOUNT', models.CharField(max_length=25)),
                ('PASSWORD', models.CharField(max_length=25)),
                ('CREATETIME', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='soiltemp',
            name='UID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.user'),
        ),
        migrations.AddField(
            model_name='soilhumi',
            name='UID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.user'),
        ),
        migrations.AddField(
            model_name='light',
            name='UID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.user'),
        ),
        migrations.AddField(
            model_name='device',
            name='UID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.user'),
        ),
        migrations.AddField(
            model_name='co2',
            name='UID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.user'),
        ),
        migrations.AddField(
            model_name='airtemp',
            name='UID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.user'),
        ),
        migrations.AddField(
            model_name='airhumi',
            name='UID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.user'),
        ),
    ]
