# Generated by Django 2.0.3 on 2018-04-08 09:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20180408_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='CREATETIME',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 4, 8, 9, 16, 32, 199666, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
