# Generated by Django 2.0.3 on 2018-04-08 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20180408_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='CREATETIME',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
