# Generated by Django 2.0.3 on 2018-04-08 09:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20180408_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='CREATETIME',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
