# Generated by Django 2.0.3 on 2018-04-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_auto_20180409_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='CREATETIME',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
