# Generated by Django 2.0.3 on 2018-04-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_auto_20180409_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODE', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='EMAIL',
            field=models.CharField(default='-', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='ACCOUNT',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='PASSWORD',
            field=models.CharField(max_length=30),
        ),
    ]
