# Generated by Django 2.0.3 on 2018-04-10 08:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_auto_20180410_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='CREATETIME',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='CODE',
            field=models.CharField(max_length=10),
        ),
    ]
