# Generated by Django 2.0.3 on 2018-04-10 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0020_auto_20180410_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='resetcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ACCOUNT', models.CharField(max_length=30)),
                ('RESETCODE', models.CharField(max_length=10, null=True)),
                ('CREATETIME', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
