# Generated by Django 2.0.3 on 2018-04-19 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0021_resetcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='co2',
            name='UID',
        ),
        migrations.DeleteModel(
            name='co2',
        ),
    ]
