# Generated by Django 2.0.4 on 2018-04-23 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0022_auto_20180419_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NODE', models.IntegerField()),
                ('LIGHT', models.IntegerField()),
                ('AIRTEMP', models.FloatField()),
                ('AIRHUMI', models.IntegerField()),
                ('SOILTEMP', models.FloatField()),
                ('SOILHUMI', models.IntegerField()),
                ('CREATETIME', models.DateTimeField(auto_now=True)),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.user')),
            ],
            options={
                'db_table': 'data_summary',
            },
        ),
        migrations.RemoveField(
            model_name='airhumi',
            name='UID',
        ),
        migrations.RemoveField(
            model_name='airtemp',
            name='UID',
        ),
        migrations.RemoveField(
            model_name='light',
            name='UID',
        ),
        migrations.RemoveField(
            model_name='soilhumi',
            name='UID',
        ),
        migrations.RemoveField(
            model_name='soiltemp',
            name='UID',
        ),
        migrations.DeleteModel(
            name='airhumi',
        ),
        migrations.DeleteModel(
            name='airtemp',
        ),
        migrations.DeleteModel(
            name='light',
        ),
        migrations.DeleteModel(
            name='soilhumi',
        ),
        migrations.DeleteModel(
            name='soiltemp',
        ),
    ]
