# Generated by Django 2.0.4 on 2018-05-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0023_auto_20180423_1732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summary',
            options={'ordering': ['-CREATETIME']},
        ),
        migrations.AddField(
            model_name='device',
            name='AUTO',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='LAMP',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='device',
            name='PUMP',
            field=models.BooleanField(),
        ),
    ]
