# Generated by Django 2.0.4 on 2018-05-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0024_auto_20180511_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='AUTO',
            new_name='AUTO_LAMP',
        ),
        migrations.AddField(
            model_name='device',
            name='AUTO_PUMP',
            field=models.BooleanField(default=True),
        ),
    ]
