# Generated by Django 2.0.4 on 2018-05-12 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0025_auto_20180511_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='UID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.user'),
        ),
    ]
